var accommodations = [
  {
    name:'The Rees Lakeside Residences',
    blurb: 'The Rees Residences; surround yourself with bespoke luxury with a unique, True South, New Zealand flavor and breathtaking Queenstown location. ',
    type:'Hotel',
    id:101,
    address:'32 Red Oaks Drive,Queenstown,9300',
    location:'Queenstown',
    phoneNunber:649342768,
    lat: -45.025969,
    long: 168.746782,
    contentGuest:'1-2 Guest',
    contentBeds:'2 Beds',
    minGuest:1,
    maxGuest:2,
    minDays:1,
    maxDays:5,
    price:157,
    image: 'images/Queenstown-hotel1.jpg',
    imageOne: 'images/Queenstown-hotel1.jpg',
    imageTwo: 'images/Queenstown-hotel2.jpg',
    imageThree: 'images/Queenstown-hotel3.jpg',
    mealsOptions:[15.00,20.00,25.00]
  },
  {
    name:'Grand Mercure Wellington',
    blurb: 'Grand Mercure Wellington brings to life the history and culture of the city through anecdotes of design, cuisine and service. ',
    type:'Hotel',
    id:102,
    address:'345 The Terrace, Te Aro, Wellington 6001',
    location:'Wellington',
    phoneNunber:649342768,
    lat: -41.293457,
    long: 174.769555,
    contentGuest:'1-2 Guest',
    contentBeds:'2 Beds',
    minGuest:1,
    maxGuest:2,
    minDays:1,
    maxDays:5,
    price:157.00,
    image: 'images/wellington-hotel1.jpg',
    imageOne: 'images/wellington-hotel1.jpg',
    imageTwo: 'images/wellington-hotel2.jpg',
    imageThree: 'images/wellington-hotel3.jpg',
    mealsOptions:[18.00,20.00,35.00]
  },
  {
    name:'ibis Budget Auckland Airport',
    blurb: 'Ibis Budget Auckland Airport is the only economy option in the airport vicinity boasting all the essentials for a short stopover. Featuring block out blinds, 24 hour reception and onsite complimentary parking facilities. ',
    type:'Hotel',
    id:103,
    address:'2 Leonard Isitt Drive, Mangere, Auckland 2150',
    location:'Auckland',
    phoneNunber:649342768,
    lat: -36.992617,
    long: 174.788165,
    contentGuest:'1-2 Guest',
    contentBeds:'2 Beds',
    minGuest:1,
    maxGuest:2,
    minDays:1,
    maxDays:5,
    price:157.00,
    image: 'images/auckland-hotel1.jpg',
    imageOne: 'images/auckland-hotel1.jpg',
    imageTwo: 'images/auckland-hotel2.jpg',
    imageThree: 'images/auckland-hotel2.jpg',
    mealsOptions:[18.00,20.00,25.00]
  },
  {
    name:'Nomads Queenstown Hostel',
    blurb: 'Nomads Queenstown Backpackers is ideally located in the heart of Queenstown, in New Zealands popular South Island holiday city.',
    type:'Hostel',
    id:104,
    address:'5/11 Church Street, South island, Queenstown 9300',
    location:'Queenstown',
    phoneNunber:649342768,
    lat: -45.032290,
    long: 168.661848,
    contentGuest:'1 Guest',
    contentBeds:'1 Bed',
    minGuest:1,
    maxGuest:1,
    minDays:1,
    maxDays:10,
    price:30.00,
    image: 'images/Queenstown-hostel1.jpg',
    imageOne: 'images/Queenstown-hostel1.jpg',
    imageTwo: 'images/Queenstown-hostel2.jpg',
    imageThree: 'images/Queenstown-hostel3.jpg',
    mealsOptions:[15.00,20.00,22.00]
  },
  {
    name:'The Setup on Dixon',
    blurb: 'Located in central Wellington, The Setup Accommodation offers guests free WiFi. It is less than 5 minutes walk from a variety of restaurants, cafes and shops',
    type:'Hostel',
    id:105,
    address:' 15 Dixon Street, Te Aro, Wellington, Wellington 6011',
    location:'Wellington',
    phoneNunber:649342768,
    lat: -41.292156,
    long: 174.778088,
    contentGuest:'1 Guest',
    contentBeds:'1 Bed',
    minGuest:1,
    maxGuest:1,
    minDays:1,
    maxDays:10,
    price:30.00,
    image: 'images/wellington-hostel1.jpg',
    imageOne: 'images/wellington-hostel1.jpg',
    imageTwo: 'images/wellington-hostel2.jpg',
    imageThree: 'images/wellington-hostel3.jpg',
    mealsOptions:[15.00,20.00,22.00]
  },
  {
    name:'TMACS Backpackers',
    blurb: ' TMACS Backpackers offers air-conditioned rooms, a shared lounge, free WiFi and a garden. Featuring a tour desk, this property also provides guests with a terrace',
    type:'Hostel',
    id:106,
    address:'118-122 Nelson St, Auckland 1010',
    location:'Auckland',
    phoneNunber:649342768,
    lat: -36.853087,
    long: 174.757880,
    contentGuest:'1 Guest',
    contentBeds:'1 Bed',
    minGuest:1,
    maxGuest:1,
    minDays:1,
    maxDays:10,
    price:30.00,
    image: 'images/auckland-hostel1.png',
    imageOne: 'images/auckland-hostel1.png',
    imageTwo: 'images/auckland-hostel2.png',
    imageThree: 'images/auckland-hostel3.png',
    mealsOptions:[22.00,26.00,32.00]
  },
  {
    name:'Autoline Motel and Apartments',
    blurb: 'Just 5 minutes’ walk from Lake Wakatipu, Autoline Queenstown Motel offers self-contained accommodation with a spa bath or a private balcony with mountain views. Guests enjoy free WiFi.',
    type:'Motel',
    id:107,
    address:'2/4 Dublin Street, Queenstown 9300',
    location:'Queenstown',
    phoneNunber:034428734,
    lat: -45.032379,
    long: 168.668744,
    contentGuest:'2-4 Guest',
    contentBeds:'4 Bed',
    minGuest:2,
    maxGuest:4,
    minDays:3,
    maxDays:10,
    price:90.00,
    image: 'images/Queenstown-motel1.jpg',
    imageOne: 'images/Queenstown-motel1.jpg',
    imageTwo: 'images/Queenstown-motel2.jpg',
    imageThree: 'images/Queenstown-motel3.jpg',
    mealsOptions:[22.00,26.00,32.00]
  },
  {
    name:'Airport Motel ',
    blurb: 'Overlooking Lyall Bay, this relaxed airport motel and conference center is less than 2 km from Wellington International Airport and 3 km from the Wellington Zoo. ',
    type:'Motel',
    id:108,
    address:' 142 Tirangi Road Rongotai, Wellington  6003 ',
    location:'Wellington',
    contentGuest:'2-4 Guest',
    contentBeds:'4 Bed',
    phoneNunber:649342768,
    lat: -41.327666,
    long: 174.801543,
    minGuest:2,
    maxGuest:4,
    minDays:3,
    maxDays:10,
    price:90.00,
    image: 'images/wellington-motel1.jpg',
    imageOne: 'images/wellington-motel1.jpg',
    imageTwo: 'images/wellington-motel2.jpg',
    imageThree: 'images/wellington-motel3.jpg',
    mealsOptions:[22.00,26.00,32.00]
  },
  {
    name:'Devonport Motel',
    blurb: 'This stylish motel, set in a residential neighbourhood, is a 3-minute walk from sandy Devonport Beach and 5 km from the landmark Sky Tower.',
    type:'Motel',
    id:109,
    address:' 11 Buchanan Street, Devonport, Auckland 0624 ',
    location:'Auckland',
    phoneNunber:094451010,
    lat: -36.829236,
    long: 174.798911,
    contentGuest:'2-4 Guest',
    contentBeds:'4 Bed',
    minGuest:2,
    maxGuest:4,
    minDays:3,
    maxDays:10,
    price:90.00,
    image: 'images/auckland-motel1.png',
    imageOne: 'images/auckland-motel1.png',
    imageTwo: 'images/auckland-motel2.png',
    imageThree: 'images/auckland-motel3.png',
    mealsOptions:[22.00,26.00,32.00]
  },
  {
    name:'Gin and Raspberry',
    blurb: 'This spacious property is a great family holiday home is only a minute drive from the access roads to the Cardrona and Snow Park ski fields.',
    type:'house',
    id:110,
    address:' Gin And Raspberry Lane, Cardrona 9381 ',
    location:'Queenstown',
    phoneNunber:094451010,
    lat: -44.872825,
    long: 169.005488,
    contentGuest:'1-4 Guest',
    contentBeds:'4 Bed',
    minGuest:1,
    maxGuest:4,
    minDays:2,
    maxDays:15,
    price:240.00,
    image: 'images/Queenstown-house1.jpg',
    imageOne: 'images/Queenstown-house1.jpg',
    imageTwo: 'images/Queenstown-house2.jpg',
    imageThree: 'images/Queenstown-house3.jpg',
    mealsOptions:[22.00,26.00,32.00]
  },
  {
    name:'Owhiro Bay haven',
    blurb: 'Private, comfortable house. Is set in Wellington, 1.4 km from Wellington Zoo. ',
    type:'house',
    id:111,
    address:'50 Owhiro Bay, Wellington City 6023,',
    location:'Wellington',
    phoneNunber:094451010,
    lat: -41.344264,
    long: 174.759773,
    contentGuest:'1-4 Guest',
    contentBeds:'4 Bed',
    minGuest:1,
    maxGuest:4,
    minDays:2,
    maxDays:15,
    price:240.00,
    image: 'images/wellington-house1.png',
    imageOne: 'images/wellington-house1.png',
    imageTwo: 'images/wellington-house2.png',
    imageThree: 'images/wellington-house3.png',
    mealsOptions:[15.00,23.00,32.00]
  },
  {
    name:'Arohanui Cabins Off Grid Luxury Mangawhai',
    blurb: 'Leave it all behind and unwind at this off grid luxury glamping site overlooking peaceful native bush and farmland.',
    type:'house',
    id:112,
    address:' 302 Devich Road, Mangawhai 0975 Auckland ',
    location:'Auckland',
    phoneNunber:094451010,
    lat: -36.147698,
    long: 174.545124,
    contentGuest:'1-4 Guest',
    contentBeds:'4 Bed',
    minGuest:1,
    maxGuest:4,
    minDays:2,
    maxDays:15,
    price:240.00,
    image: 'images/auckland-house1.jpg',
    imageOne: 'images/auckland-house1.jpg',
    imageTwo: 'images/auckland-house2.jpg',
    imageThree: 'images/auckland-house3.jpg',
    mealsOptions:[15.00,23.00,32.00]
  },
];
// console.log(accommodations[0].mealsOptions[0].lunch);
